// Marketing / lead-source options for the "How did they hear about us?" field.
// Kept in sync with the medspa_records app so reporting categories match.
export const REFERRAL_SOURCES = [
  'Billboard',
  'Business Signage / A-Frame',
  'Co-Promotions',
  'Commercial',
  'Direct Mail',
  'Email Marketing',
  'Event',
  'Facebook',
  'Family',
  'Flyer / Handout',
  'Friend',
  'Google',
  'Groupon',
  'Instagram',
  'Personal Source',
  'Phone Campaign',
  'Pinterest',
  'Print Ad',
  'QR Code',
  'SMS Campaign',
  'TikTok',
  'Walk-in',
  'Yelp',
  'YouTube',
  'Other',
]
